title: ALT
company: BaseALT
email: org@basealt.ru

description_ru: >- # this means to ignore newlines until "baseurl:"
  Компания «Базальт СПО» – разработчик российских операционных систем «Альт».
description_en: >-
  BaseALT Ltd. - ALT operating systems russian developer company.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
vk_username: altlinux
instagram_username: basealt
github_username:  altlinux
facebook_username: "Базальт-СПО-2244393775840589"
youtube_username: "UCtCfzqL49AkFYQ7JQcL_iSw"
host: 127.0.0.1

# Development by default for testing on gh-pages
environment: development

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - Makefile
  - README.md
  - images
  - start.bat

include:
  - _data

#collections_dir: _col
collections:
  sections_en:
    permalink: /en/sections/:name
    output: true
  sections_ru:
    permalink: /ru/sections/:name
    output: true
  sections:
    permalink: /:name
    output: true
  images:
    output: false

# Variable to define empty arrays in Liquid
empty_array: []

txt_main_links:
  ru: Основные загрузки
  en: Primary downloads

txt_secondary_links:
  ru: Дополнительные загрузки
  en: Additional downloads

txt_platform:
  ru: Платформа
  en: Platform

txt_download:
  ru: Скачать
  en: Download

txt_live:
  ru: Живая система
  en: Live

txt_install:
  ru: Установка
  en: Install

