title: ALT
company: BaseALT
email: org@basealt.ru

description_ru: >- # this means to ignore newlines until "baseurl:"
  Компания «Базальт СПО» – разработчик российских операционных систем «Альт».
description_en: >-
  BaseALT Ltd. - ALT operating systems russian developer company.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
instagram_username: basealt
github_username:  altlinux
host: 127.0.0.1

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - Makefile
  - README.md
  - images
  - start.bat

#collections_dir: _col
collections:
  sections_en:
    permalink: /en/sections/:name
    output: true
  sections_ru:
    permalink: /ru/sections/:name
    output: true
  sections:
    permalink: /:name
    output: true
  images:
    output: false

# Variable to define empty arrays in Liquid
empty_array: []

txt_main_links:
  ru: Основные загрузки
  en: Primary downloads

txt_secondary_links:
  ru: Дополнительные загрузки
  en: Additional downloads

txt_platform:
  ru: Платформа
  en: Platform

txt_download:
  ru: Скачать
  en: Download

